### PR TITLE
Update options for mock router creation

### PR DESCRIPTION
**Pull request by kmdmnak**
I have made changes so that the arguments passed to ```createMockRouter``` now align with those used internally by ```createConnectRouter``` .
Previously, options for specifying protocols such as ```grpc``` or ```grpcWeb```, which are available in ```createConnectRouter```, were not present. This limitation prevented changing protocols when creating mocks, which has now been addressed.

Best regards.

### CODE REVIEW

**Comment by smaye81** [comment]
Hi, @kmdmnak thanks for the PR. Can you explain a bit more about what you're trying to do with your mocks? By default, the router supports all protocols. Are you trying to specifically toggle off a protocol?

**Comment by kmdmnak** [comment]
@smaye81 Thank you for checking! 

Sorry, there was a misunderstanding on my part. 
Currently, the client side is sending requests in grpc-web binary format, but using this router results in an error message saying  ```byte stream required, but received JSON``` (caused by [this](https://github.com/connectrpc/connect-es/blob/main/packages/connect/src/protocol/universal.ts#L95)).
That's why I thought about disabling some protocols as you mentioned. 

However, upon closer inspection, I realized that the error is due to insufficient conversion of the body in the current implementation. It seems necessary to convert the body into an asynchronously iterable item at [this part](https://github.com/connectrpc/connect-playwright-es/blob/main/packages/connect-playwright/src/create-mock-router.ts#L194) to pass through assertion.

**Comment by smaye81** [comment]
Hi @kmdmnak appreciate the patience. Just to confirm, is this with a streaming RPC? Connect-Playwright only supports unary RPCs at the moment.

**Comment by kmdmnak** [comment]
@smaye81 Thank you for your confirmation!
> is this with a streaming RPC?

No. Currently, I'm only using unary RPCs.

**Comment by smaye81** [comment]
Hi @kmdmnak there is indeed a bit missing here regarding the GrpcWebTransport. I'm going to put up a PR today that hopefully fixes this. Appreciate you calling this out.

**Comment by smaye81** [comment]
@kmdmnak PR is here if you'd like to try this out and see if it works for you: https://github.com/connectrpc/connect-playwright-es/pull/100

**Comment by smaye81** [comment]
@kmdmnak We released v0.3.2 today which should hopefully fix this issue. Going to close this PR in light of that release. Please give it a try and let us know. Thanks again for reporting!

**Pull request closed without merging**
